# -*- coding: utf-8 -*-
"""preproccesing-EV01  by team stackers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQv3V1M8Cf7BKNqAylhY1Ps-Qrxkux8g
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("/content/ENVISION-RAWDATASET-HEART-TEAM STACKERS.csv")

df

df.head()

df.info()

df.describe()

df.isnull().sum()

import pandas as pd

# Load the data
df = pd.read_csv('ENVISION-RAWDATASET-HEART-TEAM STACKERS.csv')

# Convert every single null value to 0
df = df.fillna(0)

print("Null values remaining:", df.isnull().sum().sum())

df

df['unnecessary_feature'].value_counts()

df['sex'] = df['sex'].map({'male': 1, 'female': 0})

df['cp'] = df['cp'].map({'atypical angina': 0, 'asymptomatic':1,'typical angina':2,'non-anginal pain':3})

df['fbs'] = df['fbs'].map({'True': 1, 'False': 0})

df['restecg'] = df['restecg'].map({'ST-T wave abnormality': 1, 'normal': 0})

df['exang'] = df['exang'].map({'yes': 1, 'no': 0})

df['slope'] = df['slope'].map({'upsloping': 1, 'flat': 0,'downsloping':2})

df['thal'] = df['thal'].map({'fixed defect': 0, 'reversible defect': 1})

df['target'] = df['target'].fillna(0)

df.info()

df

df.describe(include="object")

import pandas as pd
from google.colab import files

# 1. Load the data
df = pd.read_csv('ENVISION-RAWDATASET-HEART-TEAM STACKERS.csv')

# 2. Fill all Null values with 0
df = df.fillna(0)

# 3. Remove Outliers using IQR for main columns
for col in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']:
    Q1, Q3 = df[col].quantile([0.25, 0.75])
    IQR = Q3 - Q1
    df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

# 4. Save and Download the file
df.to_csv('heartrisk-preproccesed data for envision.csv ', index=False)
files.download('heartrisk-preproccesed data for envision.csv ')
print("file downloaded successfully")

for i in df.select_dtypes(include="number").columns:
    # Use distplot if histplot is not available in your seaborn version
    # sns.hisplot(data=df, x=i)
    sns.histplot(df[i])  # Use distplot instead of hisplot
    plt.show()

plt.figure(figsize=(7, 5))
# Use a countplot for the 'target' column
sns.countplot(x='target', data=df, palette='viridis')

plt.title('Distribution of Heart Disease (Target Variable)', fontsize=15)
plt.xlabel('0 = No Disease, 1 = Disease Presence')
plt.ylabel('Number of Patients')
plt.show()

# We fill nulls with 0 and encode text just for this heatmap
df_temp = df.fillna(0)
for col in df_temp.select_dtypes(include=['object']).columns:
    df_temp[col] = pd.factorize(df_temp[col])[0]

plt.figure(figsize=(14, 10))
# Create the heatmap
correlation_matrix = df_temp.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)

plt.title('Correlation Heatmap of All Parameters', fontsize=15)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Load and clean
df = pd.read_csv('ENVISION-RAWDATASET-HEART-TEAM STACKERS.csv').fillna(0)
df['target'] = df['target'].round().astype(int)

# 2. Plotting
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='cp', hue='target', palette='Set1')

plt.title('Heart Disease Frequency for Chest Pain Types', fontsize=14)
plt.xlabel('Chest Pain Type (cp)', fontsize=12)
plt.ylabel('Patient Count', fontsize=12)
plt.legend(title='Heart Disease', labels=['Healthy (0)', 'Disease (1)'])
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 7))
sns.scatterplot(x='age', y='thalach', hue='target', data=df, palette='coolwarm', s=100)
plt.title('Age vs. Maximum Heart Rate (thalach) by Heart Disease Presence', fontsize=15)
plt.xlabel('Age', fontsize=12)
plt.ylabel('Maximum Heart Rate Achieved (thalach)', fontsize=12)
plt.legend(title='Heart Disease', labels=['Healthy (0)', 'Disease (1)'])
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()



plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='unnecessary_feature', hue='target', palette='Set2')
plt.title('Heart Disease Presence by Unnecessary Feature', fontsize=14)
plt.xlabel('Unnecessary Feature', fontsize=12)
plt.ylabel('Patient Count', fontsize=12)
plt.legend(title='Heart Disease', labels=['Healthy (0)', 'Disease (1)'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()